In [83]:
from io import StringIO
import pandas as pd
import re
import numpy as np

In [84]:
# Get data without the bad one
df = pd.read_csv("RamData.csv",
    on_bad_lines="skip"
)

print(df.shape)

(13890, 10)

In [85]:
df

,Name,Speed,Module,First Word Latency,CAS Latency,Price Per GB,Color,Rating,Review Count,Price
0,Crucial Pro Overclocking 32 GB,DDR5-6000,2 x 16GB,12 ns,36.0,$8.562,Black,4.5,45,$273.99
1,Corsair Vengeance RGB 32 GB,DDR5-6000,2 x 16GB,12 ns,36.0,$12.750,Black,4.5,89,$407.99
2,Corsair Vengeance LPX 32 GB,DDR4-3200,2 x 16GB,10 ns,16.0,$5.343,Black / Yellow,4.5,72,$170.99
3,G.Skill Flare X5 32 GB,DDR5-6000,2 x 16GB,12 ns,36.0,$11.406,Black,4.5,110,$365.00
4,Corsair Vengeance LPX 16 GB,DDR4-3200,2 x 8GB,10 ns,16.0,$7.062,Black / Yellow,4.5,511,$112.99
...,...,...,...,...,...,...,...,...,...,...
13885,TEAMGROUP T-Force Delta RGB 16 GB,DDR5-6000,1 x 16GB,13.333 ns,40.0,NaN,White,0.0,0,0
13886,TEAMGROUP T-Force Delta RGB 16 GB,DDR5-6000,1 x 16GB,11.333 ns,34.0,NaN,White,0.0,0,0
13887,TEAMGROUP T-Force Delta RGB 16 GB,DDR5-6000,1 x 16GB,10.667 ns,32.0,NaN,White,0.0,0,0
13888,V-Color Manta XSky RGB 32 GB,DDR5-6200,2 x 16GB,10.968 ns,34.0,NaN,White,0.0,0,0
13889,V-Color Manta XSky RGB 32 GB,DDR5-6200,2 x 16GB,10.968 ns,34.0,NaN,Silver,0.0,0,0

In [86]:
#Bad Data Isolation
bad_rows = []

with open("RamData.csv") as f:
    header = f.readline()  # skip header
    for i, line in enumerate(f, start=1):
        if line.count(",") != 9:
            bad_rows.append(line)

len(bad_rows)

22

In [87]:
for bad_row in bad_rows:
    print(bad_row)

Patriot Viper Xtreme Series, Division 2 4 GB,DDR3-1866,2 x 2GB,9.646 ns,9,$16.797,Black / Silver,0,0,$67.19

Patriot Intel Extreme Master, Limited Ed 8 GB,DDR3-1600,2 x 4GB,11.25 ns,9,,Black / Blue,4.5,8,0

Patriot Viper Xtreme Series, Division 2 4 GB,DDR3-1600,2 x 2GB,10 ns,8,$15.290,Black / Silver,0,0,$61.16

Patriot Intel Extreme Master, Limited Ed 32 GB,DDR3-1600,4 x 8GB,11.25 ns,9,,Black / Blue,5,2,0

Patriot Viper Xtreme Series, Division Vi 8 GB,DDR3-2133,2 x 4GB,10.314 ns,11,$14.599,Black / Silver,0,0,$116.79

Patriot Viper Xtreme Series, Division 4 16 GB,DDR3-2133,4 x 4GB,10.314 ns,11,,Black / Silver,0,0,0

Patriot Intel Extreme Master, Limited Ed 16 GB,DDR3-1866,2 x 8GB,10.718 ns,10,,Black / Blue,0,0,0

Patriot Intel Extreme Master, Limited Ed 32 GB,DDR3-1866,4 x 8GB,10.718 ns,10,,Black / Blue,5,1,0

Patriot Intel Extreme Master, Limited Ed 16 GB,DDR3-2133,4 x 4GB,10.314 ns,11,,Black / Blue,0,0,0

Patriot Viper Xtreme Series, Division 2 8 GB,DDR3-1600,2 x 4GB,10 ns,8,,Black / Silver,4.5,3,0

Patriot Gamer 2 Series, Division 2 Editi 16 GB,DDR3-1333,4 x 4GB,13.503 ns,9,,Black / Blue,0,0,0

Patriot Gamer 2 Series, Division 2 Editi 32 GB,DDR3-1333,4 x 8GB,13.503 ns,9,,,0,0,0

Patriot Gamer 2 Series, Division 4 Editi 8 GB,DDR3-1333,4 x 2GB,13.503 ns,9,,Black / Blue,0,0,0

Patriot Gamer 2 Series, Division 4 Editi 16 GB,DDR3-1866,4 x 4GB,9.646 ns,9,,Black / Blue,0,0,0

Patriot Gamer 2, Division 4 Edition 32 GB,DDR3-1600,4 x 8GB,11.25 ns,9,,Black / Blue,0,0,0

Patriot Viper Xtreme Series, Division 2 8 GB,DDR3-2400,2 x 4GB,9.167 ns,11,,Black / Silver,0,0,0

Patriot Viper Xtreme Series, Division 2 16 GB,DDR3-1866,2 x 8GB,9.646 ns,9,,Black / Silver,0,0,0

Patriot Intel Extreme Master, Limited Ed 8 GB,DDR3-1866,2 x 4GB,9.646 ns,9,,Black / Blue,4,1,0

Patriot Intel Extreme Master, Limited Ed 8 GB,DDR3-2133,2 x 4GB,10.314 ns,11,,Black / Blue,5,1,0

Patriot Intel Extreme Master, Limited Ed 16 GB,DDR3-1600,2 x 8GB,11.25 ns,9,,Black / Blue,4,5,0

Patriot Intel Extreme Master, Limited Ed 16 GB,DDR3-1600,4 x 4GB,11.25 ns,9,,Black / Blue,0,0,0

Patriot Intel Extreme Master, Limited Ed 16 GB,DDR3-1866,4 x 4GB,9.646 ns,9,,Black / Blue,0,0,0

In [88]:
# Fixing the bad data using RegEx
fixed = []
pattern = r"^(.*?)([A-Z]{3}\d.*)"

for bad_row in bad_rows:
    match = re.search(pattern, bad_row)
    fixedName = match.group(1).replace(",","") + ","
    fixedCombined = fixedName + match.group(2)
    fixed.append(fixedCombined)
    print(fixedCombined)

Patriot Viper Xtreme Series Division 2 4 GB,DDR3-1866,2 x 2GB,9.646 ns,9,$16.797,Black / Silver,0,0,$67.19
Patriot Intel Extreme Master Limited Ed 8 GB,DDR3-1600,2 x 4GB,11.25 ns,9,,Black / Blue,4.5,8,0
Patriot Viper Xtreme Series Division 2 4 GB,DDR3-1600,2 x 2GB,10 ns,8,$15.290,Black / Silver,0,0,$61.16
Patriot Intel Extreme Master Limited Ed 32 GB,DDR3-1600,4 x 8GB,11.25 ns,9,,Black / Blue,5,2,0
Patriot Viper Xtreme Series Division Vi 8 GB,DDR3-2133,2 x 4GB,10.314 ns,11,$14.599,Black / Silver,0,0,$116.79
Patriot Viper Xtreme Series Division 4 16 GB,DDR3-2133,4 x 4GB,10.314 ns,11,,Black / Silver,0,0,0
Patriot Intel Extreme Master Limited Ed 16 GB,DDR3-1866,2 x 8GB,10.718 ns,10,,Black / Blue,0,0,0
Patriot Intel Extreme Master Limited Ed 32 GB,DDR3-1866,4 x 8GB,10.718 ns,10,,Black / Blue,5,1,0
Patriot Intel Extreme Master Limited Ed 16 GB,DDR3-2133,4 x 4GB,10.314 ns,11,,Black / Blue,0,0,0
Patriot Viper Xtreme Series Division 2 8 GB,DDR3-1600,2 x 4GB,10 ns,8,,Black / Silver,4.5,3,0
Patriot Gamer 2 Series Division 2 Editi 16 GB,DDR3-1333,4 x 4GB,13.503 ns,9,,Black / Blue,0,0,0
Patriot Gamer 2 Series Division 2 Editi 32 GB,DDR3-1333,4 x 8GB,13.503 ns,9,,,0,0,0
Patriot Gamer 2 Series Division 4 Editi 8 GB,DDR3-1333,4 x 2GB,13.503 ns,9,,Black / Blue,0,0,0
Patriot Gamer 2 Series Division 4 Editi 16 GB,DDR3-1866,4 x 4GB,9.646 ns,9,,Black / Blue,0,0,0
Patriot Gamer 2 Division 4 Edition 32 GB,DDR3-1600,4 x 8GB,11.25 ns,9,,Black / Blue,0,0,0
Patriot Viper Xtreme Series Division 2 8 GB,DDR3-2400,2 x 4GB,9.167 ns,11,,Black / Silver,0,0,0
Patriot Viper Xtreme Series Division 2 16 GB,DDR3-1866,2 x 8GB,9.646 ns,9,,Black / Silver,0,0,0
Patriot Intel Extreme Master Limited Ed 8 GB,DDR3-1866,2 x 4GB,9.646 ns,9,,Black / Blue,4,1,0
Patriot Intel Extreme Master Limited Ed 8 GB,DDR3-2133,2 x 4GB,10.314 ns,11,,Black / Blue,5,1,0
Patriot Intel Extreme Master Limited Ed 16 GB,DDR3-1600,2 x 8GB,11.25 ns,9,,Black / Blue,4,5,0
Patriot Intel Extreme Master Limited Ed 16 GB,DDR3-1600,4 x 4GB,11.25 ns,9,,Black / Blue,0,0,0
Patriot Intel Extreme Master Limited Ed 16 GB,DDR3-1866,4 x 4GB,9.646 ns,9,,Black / Blue,0,0,0

In [89]:
fixed_df = pd.read_csv(
    StringIO("\n".join(fixed)),
    header=None
)

fixed_df.columns = df.columns

fixed_df

,Name,Speed,Module,First Word Latency,CAS Latency,Price Per GB,Color,Rating,Review Count,Price
0,Patriot Viper Xtreme Series Division 2 4 GB,DDR3-1866,2 x 2GB,9.646 ns,9,$16.797,Black / Silver,0.0,0,$67.19
1,Patriot Intel Extreme Master Limited Ed 8 GB,DDR3-1600,2 x 4GB,11.25 ns,9,NaN,Black / Blue,4.5,8,0
2,Patriot Viper Xtreme Series Division 2 4 GB,DDR3-1600,2 x 2GB,10 ns,8,$15.290,Black / Silver,0.0,0,$61.16
3,Patriot Intel Extreme Master Limited Ed 32 GB,DDR3-1600,4 x 8GB,11.25 ns,9,NaN,Black / Blue,5.0,2,0
4,Patriot Viper Xtreme Series Division Vi 8 GB,DDR3-2133,2 x 4GB,10.314 ns,11,$14.599,Black / Silver,0.0,0,$116.79
5,Patriot Viper Xtreme Series Division 4 16 GB,DDR3-2133,4 x 4GB,10.314 ns,11,NaN,Black / Silver,0.0,0,0
6,Patriot Intel Extreme Master Limited Ed 16 GB,DDR3-1866,2 x 8GB,10.718 ns,10,NaN,Black / Blue,0.0,0,0
7,Patriot Intel Extreme Master Limited Ed 32 GB,DDR3-1866,4 x 8GB,10.718 ns,10,NaN,Black / Blue,5.0,1,0
8,Patriot Intel Extreme Master Limited Ed 16 GB,DDR3-2133,4 x 4GB,10.314 ns,11,NaN,Black / Blue,0.0,0,0
9,Patriot Viper Xtreme Series Division 2 8 GB,DDR3-1600,2 x 4GB,10 ns,8,NaN,Black / Silver,4.5,3,0
10,Patriot Gamer 2 Series Division 2 Editi 16 GB,DDR3-1333,4 x 4GB,13.503 ns,9,NaN,Black / Blue,0.0,0,0
11,Patriot Gamer 2 Series Division 2 Editi 32 GB,DDR3-1333,4 x 8GB,13.503 ns,9,NaN,NaN,0.0,0,0
12,Patriot Gamer 2 Series Division 4 Editi 8 GB,DDR3-1333,4 x 2GB,13.503 ns,9,NaN,Black / Blue,0.0,0,0
13,Patriot Gamer 2 Series Division 4 Editi 16 GB,DDR3-1866,4 x 4GB,9.646 ns,9,NaN,Black / Blue,0.0,0,0
14,Patriot Gamer 2 Division 4 Edition 32 GB,DDR3-1600,4 x 8GB,11.25 ns,9,NaN,Black / Blue,0.0,0,0
15,Patriot Viper Xtreme Series Division 2 8 GB,DDR3-2400,2 x 4GB,9.167 ns,11,NaN,Black / Silver,0.0,0,0
16,Patriot Viper Xtreme Series Division 2 16 GB,DDR3-1866,2 x 8GB,9.646 ns,9,NaN,Black / Silver,0.0,0,0
17,Patriot Intel Extreme Master Limited Ed 8 GB,DDR3-1866,2 x 4GB,9.646 ns,9,NaN,Black / Blue,4.0,1,0
18,Patriot Intel Extreme Master Limited Ed 8 GB,DDR3-2133,2 x 4GB,10.314 ns,11,NaN,Black / Blue,5.0,1,0
19,Patriot Intel Extreme Master Limited Ed 16 GB,DDR3-1600,2 x 8GB,11.25 ns,9,NaN,Black / Blue,4.0,5,0
20,Patriot Intel Extreme Master Limited Ed 16 GB,DDR3-1600,4 x 4GB,11.25 ns,9,NaN,Black / Blue,0.0,0,0
21,Patriot Intel Extreme Master Limited Ed 16 GB,DDR3-1866,4 x 4GB,9.646 ns,9,NaN,Black / Blue,0.0,0,0

In [90]:
df = pd.concat([df, fixed_df], ignore_index=True)

print(df.shape)

(13912, 10)

In [91]:
df['Brand'] = df['Name'].apply(lambda x: x.split()[0]).astype('string')

In [92]:
df['Brand'].unique()

<StringArray>
[    'Crucial',     'Corsair',     'G.Skill',     'Silicon',    'Kingston',
     'Patriot',   'TEAMGROUP',       'Klevv',         'PNY',       'ADATA',
       'Lexar',     'V-Color',     'Samsung',  'Supermicro',        'OLOy',
 'Thermaltake',     'Timetec',     'GOODRAM',       'Biwin',        'Acer',
       'Netac',        'GeIL',          'SK',     'Mushkin',    'KingBank',
    'Gigabyte',      'Apacer',         'Neo',          'HP',      'Micron',
         'OCZ',      'Gloway',   'VisionTek',         'AMD',      'Wintec',
        'EVGA',      'Lenovo',        'Dell',      'Avexir',     'Addlink',
       'Antec',       'Super',       'GALAX',   'Transcend',      'YEYIAN',
         'IBM',        'KFA2',     'PROXMEM',     'Pareema',          'V7',
      'Panram',  'Compustocx',      'Apotop',     'Toshiba']
Length: 54, dtype: string

In [93]:
df['Brand'] = df['Brand'].replace("Super", "Super Talent")
df['Brand'] = df['Brand'].replace("Neo", "Neo Forza")
df['Brand'] = df['Brand'].replace("SK", "SK Hynix")

In [94]:
df['Brand'].unique()

<StringArray>
[     'Crucial',      'Corsair',      'G.Skill',      'Silicon',
     'Kingston',      'Patriot',    'TEAMGROUP',        'Klevv',
          'PNY',        'ADATA',        'Lexar',      'V-Color',
      'Samsung',   'Supermicro',         'OLOy',  'Thermaltake',
      'Timetec',      'GOODRAM',        'Biwin',         'Acer',
        'Netac',         'GeIL',     'SK Hynix',      'Mushkin',
     'KingBank',     'Gigabyte',       'Apacer',    'Neo Forza',
           'HP',       'Micron',          'OCZ',       'Gloway',
    'VisionTek',          'AMD',       'Wintec',         'EVGA',
       'Lenovo',         'Dell',       'Avexir',      'Addlink',
        'Antec', 'Super Talent',        'GALAX',    'Transcend',
       'YEYIAN',          'IBM',         'KFA2',      'PROXMEM',
      'Pareema',           'V7',       'Panram',   'Compustocx',
       'Apotop',      'Toshiba']
Length: 54, dtype: string

In [95]:
df[['Memory Type', 'Memory Speed']] = df['Speed'].str.split("-", expand=True)
df['Memory Type'] = df['Memory Type'].astype('string')
df['Memory Speed'] = df['Memory Speed'].astype(int)

In [96]:
df['First Word Latency'] = df['First Word Latency'].str.extract(r"(.+\d)").fillna(0).astype(float)
df['Price']= df['Price'].str.extract(r'(\d+\.\d+)|(\d+)')[0].fillna(0).astype(float)
df['Color'] = df['Color'].fillna("None")
df["Color"] = df["Color"].str.split("/").apply(lambda x: [c.strip() for c in x])
df['Module'] = df['Module'].astype('string')
df['Name'] = df['Name'].astype('string')

extracted = df["Module"].str.extract(r"(\d+)\s*x\s*(\d+)(\w+)")
df["Total Capacity"] = (
    extracted[0].astype(int)
    * extracted[1].astype(int)
    / extracted[2].str.lower().map({"gb": 1, "mb": 1024})
).astype(float)
df["Price Per GB"] = (df["Price"] / df["Total Capacity"]).round(2)

In [97]:
df = df.drop(columns=['Speed'])

In [98]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13912 entries, 0 to 13911
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                13912 non-null  string
 1   Module              13912 non-null  string
 2   First Word Latency  13912 non-null  float64
 3   CAS Latency         13912 non-null  float64
 4   Price Per GB        13912 non-null  float64
 5   Color               13912 non-null  object
 6   Rating              13912 non-null  float64
 7   Review Count        13912 non-null  int64
 8   Price               13912 non-null  float64
 9   Brand               13912 non-null  string
 10  Memory Type         13912 non-null  string
 11  Memory Speed        13912 non-null  int64
 12  Total Capacity      13912 non-null  float64
dtypes: float64(6), int64(2), object(1), string(4)
memory usage: 1.4+ MB

In [99]:
df.isna().sum()

Name                  0
Module                0
First Word Latency    0
CAS Latency           0
Price Per GB          0
Color                 0
Rating                0
Review Count          0
Price                 0
Brand                 0
Memory Type           0
Memory Speed          0
Total Capacity        0
dtype: int64

In [100]:
new_order = ['Name', 'Brand', 'Memory Type', 'Memory Speed', 'Module', 'Total Capacity', 'First Word Latency', 'CAS Latency', 'Price', 'Price Per GB', 'Color', 'Rating', 'Review Count']
df = df[new_order]
df

,Name,Brand,Memory Type,Memory Speed,Module,Total Capacity,First Word Latency,CAS Latency,Price,Price Per GB,Color,Rating,Review Count
0,Crucial Pro Overclocking 32 GB,Crucial,DDR5,6000,2 x 16GB,32.0,12.000,36.0,273.99,8.56,[Black],4.5,45
1,Corsair Vengeance RGB 32 GB,Corsair,DDR5,6000,2 x 16GB,32.0,12.000,36.0,407.99,12.75,[Black],4.5,89
2,Corsair Vengeance LPX 32 GB,Corsair,DDR4,3200,2 x 16GB,32.0,10.000,16.0,170.99,5.34,"[Black, Yellow]",4.5,72
3,G.Skill Flare X5 32 GB,G.Skill,DDR5,6000,2 x 16GB,32.0,12.000,36.0,365.00,11.41,[Black],4.5,110
4,Corsair Vengeance LPX 16 GB,Corsair,DDR4,3200,2 x 8GB,16.0,10.000,16.0,112.99,7.06,"[Black, Yellow]",4.5,511
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13907,Patriot Intel Extreme Master Limited Ed 8 GB,Patriot,DDR3,1866,2 x 4GB,8.0,9.646,9.0,0.00,0.00,"[Black, Blue]",4.0,1
13908,Patriot Intel Extreme Master Limited Ed 8 GB,Patriot,DDR3,2133,2 x 4GB,8.0,10.314,11.0,0.00,0.00,"[Black, Blue]",5.0,1
13909,Patriot Intel Extreme Master Limited Ed 16 GB,Patriot,DDR3,1600,2 x 8GB,16.0,11.250,9.0,0.00,0.00,"[Black, Blue]",4.0,5
13910,Patriot Intel Extreme Master Limited Ed 16 GB,Patriot,DDR3,1600,4 x 4GB,16.0,11.250,9.0,0.00,0.00,"[Black, Blue]",0.0,0
13911,Patriot Intel Extreme Master Limited Ed 16 GB,Patriot,DDR3,1866,4 x 4GB,16.0,9.646,9.0,0.00,0.00,"[Black, Blue]",0.0,0

In [101]:
df["Brand"].unique()

<StringArray>
[     'Crucial',      'Corsair',      'G.Skill',      'Silicon',
     'Kingston',      'Patriot',    'TEAMGROUP',        'Klevv',
          'PNY',        'ADATA',        'Lexar',      'V-Color',
      'Samsung',   'Supermicro',         'OLOy',  'Thermaltake',
      'Timetec',      'GOODRAM',        'Biwin',         'Acer',
        'Netac',         'GeIL',     'SK Hynix',      'Mushkin',
     'KingBank',     'Gigabyte',       'Apacer',    'Neo Forza',
           'HP',       'Micron',          'OCZ',       'Gloway',
    'VisionTek',          'AMD',       'Wintec',         'EVGA',
       'Lenovo',         'Dell',       'Avexir',      'Addlink',
        'Antec', 'Super Talent',        'GALAX',    'Transcend',
       'YEYIAN',          'IBM',         'KFA2',      'PROXMEM',
      'Pareema',           'V7',       'Panram',   'Compustocx',
       'Apotop',      'Toshiba']
Length: 54, dtype: string

In [102]:
df

,Name,Brand,Memory Type,Memory Speed,Module,Total Capacity,First Word Latency,CAS Latency,Price,Price Per GB,Color,Rating,Review Count
0,Crucial Pro Overclocking 32 GB,Crucial,DDR5,6000,2 x 16GB,32.0,12.000,36.0,273.99,8.56,[Black],4.5,45
1,Corsair Vengeance RGB 32 GB,Corsair,DDR5,6000,2 x 16GB,32.0,12.000,36.0,407.99,12.75,[Black],4.5,89
2,Corsair Vengeance LPX 32 GB,Corsair,DDR4,3200,2 x 16GB,32.0,10.000,16.0,170.99,5.34,"[Black, Yellow]",4.5,72
3,G.Skill Flare X5 32 GB,G.Skill,DDR5,6000,2 x 16GB,32.0,12.000,36.0,365.00,11.41,[Black],4.5,110
4,Corsair Vengeance LPX 16 GB,Corsair,DDR4,3200,2 x 8GB,16.0,10.000,16.0,112.99,7.06,"[Black, Yellow]",4.5,511
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13907,Patriot Intel Extreme Master Limited Ed 8 GB,Patriot,DDR3,1866,2 x 4GB,8.0,9.646,9.0,0.00,0.00,"[Black, Blue]",4.0,1
13908,Patriot Intel Extreme Master Limited Ed 8 GB,Patriot,DDR3,2133,2 x 4GB,8.0,10.314,11.0,0.00,0.00,"[Black, Blue]",5.0,1
13909,Patriot Intel Extreme Master Limited Ed 16 GB,Patriot,DDR3,1600,2 x 8GB,16.0,11.250,9.0,0.00,0.00,"[Black, Blue]",4.0,5
13910,Patriot Intel Extreme Master Limited Ed 16 GB,Patriot,DDR3,1600,4 x 4GB,16.0,11.250,9.0,0.00,0.00,"[Black, Blue]",0.0,0
13911,Patriot Intel Extreme Master Limited Ed 16 GB,Patriot,DDR3,1866,4 x 4GB,16.0,9.646,9.0,0.00,0.00,"[Black, Blue]",0.0,0

In [103]:
df["Total Capacity"].unique()

array([3.20e+01, 1.60e+01, 6.40e+01, 8.00e+00, 1.92e+02, 1.28e+02,
       4.00e+00, 9.60e+01, 4.80e+01, 2.56e+02, 5.12e+02, 2.00e+00,
       1.00e+00, 2.40e+01, 3.00e+00, 1.20e+01, 5.00e-01, 3.84e+02,
       6.00e+00])

In [104]:
brands = df["Brand"].unique()

brands_df = pd.Series(brands, name="Name").to_frame()

brands_df["Id"] = brands_df.index

brands_df = brands_df[["Id", "Name"]]

brands_df.to_csv("brands.csv", index=False)

In [105]:
brand_map = dict(zip(brands_df["Name"], brands_df["Id"]))

df["BrandId"] = df["Brand"].map(brand_map)

In [106]:
brand_map

{'Crucial': 0,
 'Corsair': 1,
 'G.Skill': 2,
 'Silicon': 3,
 'Kingston': 4,
 'Patriot': 5,
 'TEAMGROUP': 6,
 'Klevv': 7,
 'PNY': 8,
 'ADATA': 9,
 'Lexar': 10,
 'V-Color': 11,
 'Samsung': 12,
 'Supermicro': 13,
 'OLOy': 14,
 'Thermaltake': 15,
 'Timetec': 16,
 'GOODRAM': 17,
 'Biwin': 18,
 'Acer': 19,
 'Netac': 20,
 'GeIL': 21,
 'SK Hynix': 22,
 'Mushkin': 23,
 'KingBank': 24,
 'Gigabyte': 25,
 'Apacer': 26,
 'Neo Forza': 27,
 'HP': 28,
 'Micron': 29,
 'OCZ': 30,
 'Gloway': 31,
 'VisionTek': 32,
 'AMD': 33,
 'Wintec': 34,
 'EVGA': 35,
 'Lenovo': 36,
 'Dell': 37,
 'Avexir': 38,
 'Addlink': 39,
 'Antec': 40,
 'Super Talent': 41,
 'GALAX': 42,
 'Transcend': 43,
 'YEYIAN': 44,
 'IBM': 45,
 'KFA2': 46,
 'PROXMEM': 47,
 'Pareema': 48,
 'V7': 49,
 'Panram': 50,
 'Compustocx': 51,
 'Apotop': 52,
 'Toshiba': 53}

In [107]:
brand_index = df.columns.get_loc("Brand")

df["BrandId"] = df["Brand"].map(brand_map)
df.drop(columns=["Brand"], inplace=True)
df.insert(brand_index, "BrandId", df.pop("BrandId"))

In [108]:

columns = [
    "Name",
    "BrandId",
    "Memory Type",
    "Memory Speed",
    "Module",
    "Total Capacity",
    "First Word Latency",
    "CAS Latency",
    "Rating",
    "Review Count",
    "Color",
    "Price",
    "Price Per GB"
]

df = df[columns]

In [109]:
df

,Name,BrandId,Memory Type,Memory Speed,Module,Total Capacity,First Word Latency,CAS Latency,Rating,Review Count,Color,Price,Price Per GB
0,Crucial Pro Overclocking 32 GB,0,DDR5,6000,2 x 16GB,32.0,12.000,36.0,4.5,45,[Black],273.99,8.56
1,Corsair Vengeance RGB 32 GB,1,DDR5,6000,2 x 16GB,32.0,12.000,36.0,4.5,89,[Black],407.99,12.75
2,Corsair Vengeance LPX 32 GB,1,DDR4,3200,2 x 16GB,32.0,10.000,16.0,4.5,72,"[Black, Yellow]",170.99,5.34
3,G.Skill Flare X5 32 GB,2,DDR5,6000,2 x 16GB,32.0,12.000,36.0,4.5,110,[Black],365.00,11.41
4,Corsair Vengeance LPX 16 GB,1,DDR4,3200,2 x 8GB,16.0,10.000,16.0,4.5,511,"[Black, Yellow]",112.99,7.06
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13907,Patriot Intel Extreme Master Limited Ed 8 GB,5,DDR3,1866,2 x 4GB,8.0,9.646,9.0,4.0,1,"[Black, Blue]",0.00,0.00
13908,Patriot Intel Extreme Master Limited Ed 8 GB,5,DDR3,2133,2 x 4GB,8.0,10.314,11.0,5.0,1,"[Black, Blue]",0.00,0.00
13909,Patriot Intel Extreme Master Limited Ed 16 GB,5,DDR3,1600,2 x 8GB,16.0,11.250,9.0,4.0,5,"[Black, Blue]",0.00,0.00
13910,Patriot Intel Extreme Master Limited Ed 16 GB,5,DDR3,1600,4 x 4GB,16.0,11.250,9.0,0.0,0,"[Black, Blue]",0.00,0.00
13911,Patriot Intel Extreme Master Limited Ed 16 GB,5,DDR3,1866,4 x 4GB,16.0,9.646,9.0,0.0,0,"[Black, Blue]",0.00,0.00

In [110]:
df.index.name = "Id"
df.to_csv("RamDataClean.csv", index=True)